name: Provision k8s Cluster and Ingress/LB

on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}

jobs:                                            
  release:                                       
    name: Release                                
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout                                  
        uses: actions/checkout@v4                       

      - name: Configure AWS credentials                          
        uses: aws-actions/configure-aws-credentials@v4         
        with:                                                    
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}        
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Provision k8s cluster
        run: terraform apply -auto-approve

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      
      - name: Install helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: 'v3.13.3'
        id: install
      
      - name: Install nginx ingress and load balancer
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && \
          helm upgrade -i --set controller.service.type=LoadBalancer \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
          --set controller.autoscaling.maxReplicas=1 ingress-nginx ingress-nginx/ingress-nginx \
          --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-internal"="true"